CREATE TABLE "section_b" (
  "id" int PRIMARY KEY
);

CREATE TABLE "standard_file_status" (
  "id" int PRIMARY KEY,
  "section_b_id" int
);

CREATE TABLE "standard_file" (
  "standard_file_id" int PRIMARY KEY,
  "file_name" varchar,
  "standard_file_status_id" int
);

CREATE TABLE "base_issues" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issue" varchar
);

CREATE TABLE "storage_issues" (
  "id" int PRIMARY KEY,
  "section_b_id" int
);

CREATE TABLE "nsop_storage_status" (
  "nsop_storage_status_id" int PRIMARY KEY,
  "name" varchar,
  "status" varchar,
  "base_issue_id" int
);

CREATE TABLE "navigation_archival" (
  "archivals_id" int PRIMARY KEY,
  "section_b_id" int
);

CREATE TABLE "archival_base_class" (
  "archivals_id" int PRIMARY KEY,
  "size" int,
  "name" varchar,
  "status" varchar
);

CREATE TABLE "uere" (
  "chain" char,
  "satellite" varchar,
  "base_measurement_id" int PRIMARY KEY
);

CREATE TABLE "measurement" (
  "base_measurement_id" int PRIMARY KEY,
  "measurement_section_b" int
);

CREATE TABLE "base_measurement" (
  "base_measurement_id" int PRIMARY KEY,
  "location" varchar,
  "server" varchar,
  "value" int
);

CREATE TABLE "user_position" (
  "base_measurement_id" int PRIMARY KEY
);

CREATE TABLE "navic_performance_details" (
  "id" int PRIMARY KEY,
  "created_at" timestamp,
  "modified_at" timestamp,
  "section_a_id" int,
  "section_b_id" int,
  "section_c_id" int,
  "section_d_id" int,
  "section_e_id" int,
  "section_f_id" int,
  "section_g_id" int,
  "section_h_id" int
);

ALTER TABLE "standard_file_status" ADD FOREIGN KEY ("id") REFERENCES "base_issues" ("id");

ALTER TABLE "standard_file_status" ADD FOREIGN KEY ("section_b_id") REFERENCES "section_b" ("id");

ALTER TABLE "standard_file" ADD FOREIGN KEY ("standard_file_status_id") REFERENCES "standard_file_status" ("id");

ALTER TABLE "base_issues" ADD FOREIGN KEY ("id") REFERENCES "section_b" ("id");

ALTER TABLE "storage_issues" ADD FOREIGN KEY ("id") REFERENCES "base_issues" ("id");

ALTER TABLE "storage_issues" ADD FOREIGN KEY ("section_b_id") REFERENCES "section_b" ("id");

ALTER TABLE "nsop_storage_status" ADD FOREIGN KEY ("nsop_storage_status_id") REFERENCES "storage_issues" ("id");

ALTER TABLE "navigation_archival" ADD FOREIGN KEY ("section_b_id") REFERENCES "section_b" ("id");

ALTER TABLE "archival_base_class" ADD FOREIGN KEY ("archivals_id") REFERENCES "navigation_archival" ("archivals_id");

ALTER TABLE "uere" ADD FOREIGN KEY ("base_measurement_id") REFERENCES "measurement" ("base_measurement_id");

ALTER TABLE "measurement" ADD FOREIGN KEY ("base_measurement_id") REFERENCES "base_measurement" ("base_measurement_id");

ALTER TABLE "section_b" ADD FOREIGN KEY ("id") REFERENCES "measurement" ("measurement_section_b");

ALTER TABLE "user_position" ADD FOREIGN KEY ("base_measurement_id") REFERENCES "measurement" ("base_measurement_id");

ALTER TABLE "navic_performance_details" ADD FOREIGN KEY ("section_b_id") REFERENCES "section_b" ("id");
